---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-hackathon
  template:
    metadata:
      labels:
        app: azure-hackathon
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-hackathon
        image: projectnodejs.azurecr.io/projectnodejs:master-18
        resources:
          requests:
            cpu: 1
            memory: 500m
          limits:
            cpu: 1
            memory: 500m
        ports:
        - containerPort: 3000
       
---
apiVersion: v1
kind: Service
metadata:
  name: public-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hackathon-public
